# This GitHub action can publish assets for release when a tag is created.
# Currently, it's setup to run on any tag that matches the pattern "v*" (ie. v0.1.0).

name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: make install
      shell: bash

    - name: Run tests
      run: make test
      shell: bash

    - name: Build package
      run: make build
      shell: bash

    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

    - name: Get current version
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      id: get-version
      run: echo "::set-output name=CURRENT_VERSION::$(cat setup.cfg | head -2 | tail -1 | awk -F= '{print $2}'| sed 's/ //g')"

    - name: Create Release
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: softprops/action-gh-release@v0.1.13
      with:
        name: Release v${{ steps.get-version.outputs.CURRENT_VERSION }}
        tag_name: v${{ steps.get-version.outputs.CURRENT_VERSION }}
        draft: true
        prerelease: true
        generate_release_notes: true